repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ["--", "--check"]
      - id: clippy
        args: ["--all-features", "--", "-D", "warnings"]
  - repo: local
    hooks:
      - id: cargo-nextest
        name: cargo nextest run --all-features
        entry: cargo nextest run --all-features
        language: system
        pass_filenames: false
      - id: cargo-doc-tests
        name: cargo test --doc --all-features
        entry: cargo test --doc --all-features
        language: system
        pass_filenames: false
